name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          bash build.sh
      - name: upload artifact nothing-spacewar-boot.img
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: nothing-spacewar-boot-img
          path: /tmp/artifacts/nothing-spacewar-boot.img
      - name: upload artifact nothing-spacewar.img
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: nothing-spacewar-img
          path: /tmp/artifacts/nothing-spacewar.img

